;Arquivo config.ini para o projeto Modbus Getter

[serial]
; Configurações da comunicação serial para o dispositivo Modbus
; Porta serial (ex.: adaptador USB-serial)
port = /dev/ttyUSB0
; Velocidade da conexão em bits por segundo
baudrate = 57600
; Tempo de espera (em segundos) para resposta da leitura
timeout = 0.75
; Identificador do dispositivo Modbus escravo
slave_id = 1

[tcp]
; Configurações da comunicação TCP para o dispositivo Modbus
; Endereço IP do dispositivo ou gateway Modbus TCP
host = 192.168.0.7 
; Porta padrão para conexões Modbus TCP 
port = 502
; Tempo de espera (em segundos) para resposta da leitura
timeout = 2.0
; Identificador do dispositivo, se aplicável 
slave_id = 1

[database.local]
; Configurações para conexão com o banco de dados local (ex.: PostgreSQL)
; Endereço do servidor de banco de dados
host = localhost 
; Porta de acesso ao banco de dados 
port = 5432 
; Nome do usuário para autenticação
user = usuario 
; Senha de acesso (em ambiente de produção, use senhas fortes) 
password = senha 
 ; Nome do banco de dados que será utilizado 
database = banco 
