{
 "title": "Monitoramento",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Tensão",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"UrmsA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"UrmsA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Corrente",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"IrmsA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"IrmsA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Potência Ativa",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"PotAtivA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"PotAtivA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [
      "time",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Potencia reativa ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"PotReatA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"PotReatA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Potencia aparente",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"PotAparA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"PotAparA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Fator de potência",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"FatPotA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"FatPotA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Frequencia",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\njson_extract(value, '$.value') as \"Frequencia\"\nFROM data\nwhere point=\"FreqA\"",
     "rawQueryText": "SELECT\njson_extract(value, '$.value') as \"Frequencia\"\nFROM data\nwhere point=\"FreqA\""
    }
   ]
  },
  {
   "title": "Potência Ativa",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"PotAtivA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"PotAtivA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [
      "time",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Tensão",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"UrmsA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"UrmsA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Corrente",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"IrmsA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"IrmsA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Fator de Potência",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "queryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"FatPotA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "rawQueryText": "SELECT \"datetime\" AS time,\njson_extract(value, '$.value') as \"Fase A\"\nFROM data\nwhere point=\"FatPotA\" AND\n\"datetime\" > ${__from}/1000 AND\n\"datetime\" < ${__to}/1000",
     "timeColumns": [ "time" ]
    }
   ]
  }
 ]
}